name: pull-request-workflow
on: 
  pull_request: 
    types: [opened] # pull_request가 생성된 시점에만 업데이트 해주고 싶을때

jobs: 
    pull-request-job: 
        runs-on: ubuntu-latest 
        steps: 
        - name: step1 
          run: echo hello world
        - name: step2
          run: | 
            echo hello world
            echo github action