name: push-workflow(test 1)
on: push

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1-test1
      run: echo hello world
    - name: step2-test2
      run: |
        echo hello world
        echo github action-test
    
