name: push-workflow 1 # 액션창에서 표현될 명칭 (생략가능)
on: push #어떤 이벤트로 인해 깃허브액션을 트리거 시킬지

jobs: # 실행시킬 job의 집합 (필수값)
    push-job: 
        runs-on: ubuntu-latest #job 안에 실행시킬 runner 지정
        steps: # step의 집합
        - name: step1 # step의 이름 (생략가능)
          run: echo hello world
        - name: step2
          run: | # | 사용시 멀티라인 커멘드 사용가능
            echo hello world
            echo github action