name: cicd-1
on: 
  pull_request:
    type: [opened, synchronize, closed] # close를 정의해야 merge될 때 동작제어 가능
    branches: [dev]
    paths:
    - 'my-app/**'

jobs: 
  test: # ci를 위해 실행하는 job
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

  image-build: # pr이 merge되면 실행 (cd단계)
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

  deploy: # image-bulid 잡이 성공한 다음 실행 (cd단계)
    runs-on: ubuntu-latest
    needs: [ image-build ]
    steps:
    - name: checkout
      uses: actions/checkout@v4