name: my-app cicd-2
on:
  pull_request:
    types: [opened, synchronize, closed] #closed를 포함해야 merge시 동작
    branches: [dev, main]
    paths:
      - "my-app/**"

jobs:
  test:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      # - name: setup-node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # - name: Cache Node.js modules
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-
      # - name: Install dependencies
      #   run: | # npm ci는 package-lock.json에 지정된 정확한 버전을 설치한다.(package-lock.json고정)
      #     cd my-app
      #     npm ci
      # - name: npm build
      #   run: |
      #     cd my-app
      #     npm run build

  set-environment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment}}
    steps:
    - name: set env
      id: set-env
      run: |
        echo ${{ github.base_ref }}
        echo "environment=dev" >> $GITHUB_OUTPUT

        if [[ ${{ github.base_ref }} == "main" ]]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
        fi
    - name: check env
      run: echo ${{ steps.set-env.outputs.environment }}
    
  image-build:
    runs-on: ubuntu-latest
    needs: [set-environment]
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: ["${{ needs.set-evnironment.outputs.environment }}"]
    environment: ${{ matrix.environment }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      # - name: Configure AWS Credentials
      #   id: credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-region: ${{ vars.AWS_REGION }}
      #     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2
      #   with:
      #     mask-password: 'true'
      # - name: docker build & push
      #   run: |
      #     docker build -f Dockerfile --tag ${{secrets.REGISTRY }}/${{ vars.REPOSITORY }}:${{github.sha}} .
      #     docker push ${{ secrets.REGISTRY }}/${{ vars.REPOSITORY}}:${{github.sha}}

  deploy:
    runs-on: ubuntu-latest
    needs: [set-environment, image-build]
    permissions: # aws oidc설정을 위해 permission 정의
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: ["${{ needs.set-environment.outputs.environment }}"]
    environment: ${{ matrix.environment }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      # - name: Configure AWS Credentials
      #   id: credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-region: ${{ vars.AWS_REGION }}
      #     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      # - name: setup kuberctl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: latest
      # - name: setup helm
      #   uses: azure/setup-helm@v3
      #   with:
      #     version: v3.11.1
      # - name: access kubernetes
      #   run: |
      #     aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }}
      # - name: deploy
      #   id: status
      #   run: |
      #     helm upgrade --install my-app kubernetes/my-app --create-namespace --namespace my-app-${{ vars.SUFFIX }} \
      #     --set image.tag=${{ github.sha }} \
      #     --set image.repository=${{ secrets.REGISTRY }}/${{ vars.REPOSITORY }}
      # - name: notify
      #   if: always()
      #   uses: slackapi/slack-github-action@1.24.0
      #   with:
      #     payload: |
      #       {
      #         "text": "message",
      #         "blocks": [
      #           {
      #             "text": "message",
      #             "blocks": [
      #               {
      #                 "type": "section",
      #                 "text": {
      #                   "type": "mrkdwn",
      #                   "text": "Environment : ${{ needs.set-environment.outputs.environment}}, Deploy Result : ${{ steps.status.outcome }}, Repository"
      #                 }
      #               }
      #             ]
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


  create-pr:
    if: needs.set-environment.outputs.environment == 'dev'
    runs-on: ubuntu-latest
    needs: [set-environment, deploy]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: gh auth login
        run: |
          ehco ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
      - name: create branch
        run: |
          git checkout -b release/${{ github.run_id }}
          git push origin release/${{ github.run_id }}
      - name: create pr
        run: |
          gh pr create --base main --head release/${{ github.run_id }} --title "release/${{ github.run_id }} -> main" --body "release pr"
