name: context-workflow
on: workflow_dispatch

jobs:
  context-to-check-github-context:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        run: echo '${{ toJson(github) }}'
      - name: github repository name
        run: echo '${{ toJson(github.repository) }}'
      - name: github repository owner
        run: echo '${{ toJson(github.repository_owner) }}'
