name: create-repo
on: 
  workflow-dispatch:
    inputs:
      prefix:
        description: 'set repo prefix'
        required: true
        default: 'service'
        type: choice
        options: 
        - example
        - service
      name:
        description: 'set repo name'
        required: true
        default: 'github-actions'
        type: string

jpbs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
    - name: gh auth login
      run: |
        echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
    - name: create-repo
      run: |
        gh repo create heesun-action/${{ inputs.prefix }}-${{ inputs.name }} -- public --add-readme