name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "Prefix for the repository name"
        required: true
        default: "service"
        type: choice
        options:
          - exmaple
          - service
      name:
        description: "set repo name"
        required: true
        default: "github-actions"
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
      - name: create-repo
        id: create-repo
        run: |
          gh repo create june-github-action-practice/${{ inputs.prefix }}-${{ inputs.name }} --public  --add-readme
      - name: Set color based on outcome
        id: set-color
        run: |
          if [ "${{ steps.create-repo.outcome }}" == "success" ]; then
            echo "slack_color=#36a64f" >> $GITHUB_ENV
          else
            echo "slack_color=#FF0000" >> $GITHUB_ENV
          fi
      - name: Slack message
        if: always()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "attachments": [{
                "pretext": "A new repository has been created",
                "color": "${{ env.slack_color }}",
                "fields": [
                    {
                        "title": "Create repo result ${{ steps.create-repo.outcome }}",
                        "value": "${{ inputs.prefix }}-${{ inputs.name }}",
                        "short": true
                        }
                    ]
                  }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
