name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'setName'
        require: true
        default: 'github-actions'
        type: string
      environment:
        description: 'setEnv'
        require: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  workflow-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello
      - name: step2
        run: |
          echo ${{ inputs.name }}
          echo ${{ inputs.env }}
